wmic product where name="Blend for Visual Studio SDK for .NET 4.5" call uninstall
wmic product where name="Blend for Visual Studio SDK for Silverlight 5" call uninstall
wmic product where name="Entity Framework Tools for Visual Studio 2013" call uninstall
wmic product where name="IIS 8.0 Express" call uninstall
wmic product where name="Microsoft .NET Framework 4 Multi-Targeting Pack" call uninstall
wmic product where name="Microsoft .NET Framework 4.5 Multi-Targeting Pack" call uninstall
wmic product where name="Microsoft .NET Framework 4.5 SDK" call uninstall
wmic product where name="Microsoft .NET Framework 4.5.1 Multi-Targeting Pack" call uninstall
wmic product where name="Microsoft .NET Framework 4.5.1 Multi-Targeting Pack (ENU)" call uninstall
wmic product where name="Microsoft .NET Framework 4.5.1 SDK" call uninstall
wmic product where name="Microsoft Exchange Web Services Managed API 2.0" call uninstall
wmic product where name="Microsoft Expression Blend SDK for .NET 4" call uninstall
wmic product where name="Microsoft Help Viewer 2.1" call uninstall
wmic product where name="Microsoft Identity Extensions" call uninstall
wmic product where name="Microsoft Silverlight 5 SDK" call uninstall
wmic product where name="Microsoft SQL Server 2012 Command Line Utilities" call uninstall
wmic product where name="Microsoft SQL Server 2012 Data-Tier App Framework" call uninstall
wmic product where name="Microsoft SQL Server 2012 Data-Tier App Framework  (x64)" call uninstall
wmic product where name="Microsoft SQL Server 2012 Express LocalDB" call uninstall
wmic product where name="Microsoft SQL Server 2012 Management Objects" call uninstall
wmic product where name="Microsoft SQL Server 2012 Management Objects  (x64)" call uninstall
wmic product where name="Microsoft SQL Server 2012 Native Client" call uninstall
wmic product where name="Microsoft SQL Server 2012 T-SQL Language Service" call uninstall
wmic product where name="Microsoft SQL Server 2012 Transact-SQL ScriptDom" call uninstall
wmic product where name="Microsoft SQL Server Compact 4.0 SP1 x64 ENU" call uninstall
wmic product where name="Microsoft SQL Server Data Tools - enu (12.0.30919.1)" call uninstall
wmic product where name="Microsoft SQL Server Data Tools Build Utilities - enu (12.0.30919.1)" call uninstall
wmic product where name="Microsoft SQL Server System CLR Types" call uninstall
wmic product where name="Microsoft SQL Server System CLR Types (x64)" call uninstall
wmic product where name="Microsoft System CLR Types for SQL Server 2012" call uninstall
wmic product where name="Microsoft System CLR Types for SQL Server 2012 (x64)" call uninstall
wmic product where name="Microsoft Visual C++ 2012 x64 Additional Runtime - 11.0.50727" call uninstall
wmic product where name="Microsoft Visual C++ 2012 x64 Minimum Runtime - 11.0.50727" call uninstall
wmic product where name="Microsoft Visual Studio 2010 Tools for Office Runtime (x64)" call uninstall
wmic product where name="Microsoft Web Deploy 3.5" call uninstall
wmic product where name="Open XML SDK 2.5 for Microsoft Office" call uninstall
wmic product where name="Prerequisites for SSDT" call uninstall
wmic product where name="Tools for .Net 3.5" call uninstall
wmic product where name="Visual Studio Extensions for Windows Library for JavaScript" call uninstall
wmic product where name="WCF RIA Services V1.0 SP2" call uninstall
wmic product where name="Windows XP Targeting with C++" call uninstall
pause