wmic product where name="IIS 8.0 Express" call uninstall
wmic product where name="Microsoft .NET Framework 4 Multi-Targeting Pack" call uninstall
wmic product where name="Microsoft .NET Framework 4.5 Multi-Targeting Pack" call uninstall
wmic product where name="Microsoft .NET Framework 4.5 SDK - 简体中文 语言包" call uninstall
wmic product where name="Microsoft .NET Framework 4.5 SDK" call uninstall
wmic product where name="Microsoft .NET Framework 4.5.1" call uninstall
wmic product where name="Microsoft .NET Framework 4.5.1 (CHS)" call uninstall
wmic product where name="Microsoft .NET Framework 4.5.1 Multi-Targeting Pack" call uninstall
wmic product where name="Microsoft .NET Framework 4.5.1 SDK" call uninstall
wmic product where name="Microsoft .NET Framework 4.5.1 SDK（简体中文）" call uninstall
wmic product where name="Microsoft .NET Framework 4.5.1 多目标包(简体中文)" call uninstall
wmic product where name="Microsoft Exchange Web Services Managed API 2.1" call uninstall
wmic product where name="Microsoft Help Viewer 2.1" call uninstall
wmic product where name="Microsoft Help Viewer 2.1 语言包 - CHS" call uninstall
wmic product where name="Microsoft Identity Extensions" call uninstall
wmic product where name="Microsoft Silverlight" call uninstall
wmic product where name="Microsoft Silverlight 5 SDK - CHS" call uninstall
wmic product where name="Microsoft SQL Server 2012 Express LocalDB" call uninstall
wmic product where name="Microsoft SQL Server 2012 Native Client" call uninstall
wmic product where name="Microsoft SQL Server 2012 T-SQL Language Service" call uninstall
wmic product where name="Microsoft SQL Server 2012 Transact-SQL ScriptDom" call uninstall
wmic product where name="Microsoft SQL Server 2012 管理对象" call uninstall
wmic product where name="Microsoft SQL Server 2012 命令行实用工具" call uninstall
wmic product where name="Microsoft SQL Server 2012 数据层应用程序框架" call uninstall
wmic product where name="Microsoft SQL Server Compact 4.0 SP1 简体中文版" call uninstall
wmic product where name="Microsoft SQL Server Data Tools - CHS (12.0.30919.1)" call uninstall
wmic product where name="Microsoft SQL Server Data Tools Build Utilities - CHS (12.0.30919.1)" call uninstall
wmic product where name="Microsoft SQL Server System CLR Types" call uninstall
wmic product where name="Microsoft System CLR Types for SQL Server 2012" call uninstall
wmic product where name="Microsoft Visual Studio 2010 Tools for Office Runtime (x86)" call uninstall
wmic product where name="Microsoft Visual Studio 2010 Tools for Office Runtime (x86) Language Pack - CHS" call uninstall
wmic product where name="Microsoft Web Deploy 3.5" call uninstall
wmic product where name="Open XML SDK 2.5 for Microsoft Office" call uninstall
wmic product where name="SharePoint Client Components" call uninstall
wmic product where name="SSDT 必备组件" call uninstall
wmic product where name="WCF RIA Services V1.0 SP2" call uninstall
wmic product where name="Workflow Manager Client 1.0" call uninstall
pause